### PR TITLE
feat: add support for Altinn 2 code lists

### PR DESCRIPTION
**Pull request by RonnyB71**
When converting altinn2 apps to altinn3 we also need to convert the shared code lists. As there already exist a simple JSON api for the old code lists managed in TUL `https://www.altinn.no/api/metadata/codelists/{Id}{version}?language={langCode}`, I think it makes sense to expose this as a standard functionality to speed up conversion. When the closing of TUL comes closer you can consider creating a new interface for managing the lists (Pull requests to a github repo), or design a full new solution. 

## Description
This enables apps to easily continue using the same code lists from previous schemas by adding the following code to their `Startup.cs`.

```csharp
using Altinn.App.PlatformServices.Options;
.....
            services.AddAltinn2CodeList(builder => {
                builder.Add(
                    id: "ASF_Land",
                    transform: (code) => new (){Value = code.Code, Label=code.Value1},
                    // filter: (code) => int.Parse(code.Value3) > 100,
                    codeListVersion: 2758,
                    metadataApiId: "ASF_land"
                );
            });
```

## Fixes
- The first commit is part of the solution for #7903 

## Verification
- [x] **Your** code builds clean without any errors or warnings
- [ ] Manual testing done (required)
- [ ] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [ ] All tests run green

## Documentation
- [ ] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)
- [ ] Changelog is updated with a separate linked PR 
  - [ ] [altinn-app-frontend](https://docs.altinn.studio/community/changelog/app-frontend/)- (if applicable)
  - [ ] [nuget-packages](https://docs.altinn.studio/community/changelog/app-nuget/) - (if applicable)

### CODE REVIEW

**Comment by RonnyB71** [comment]
@ivarne here is the branch for you changes. Could you take a look at the test coverage for you changes? We have changed the fork pipeline so you should get a test coverage report there as well. If you fork this branch then I'll just merge back to this once you're done. Let me know if you need any assistance.

**Comment by RonnyB71** [comment]
@ivarne regarding my last comment about tests you can ignore the areas of the existing like AppBase. I'm implementing the missing pieces to generate the PDF correctly now and will add tests for those areas. But test coverage you your stuff would be good to have.

**Comment by ivarne** [comment]
I'm not very experienced writing tests. What do you think I should focus on here?

Possible focus areas:
* Service registration works, and correctly stores and provides the `filter` and `map` function.
* `metadata/codelists` endpoint still works and returns data that matches the definitions.
* Memory cache works correctly
* filter and map is correctly applied.

Do you think it is OK to actually call the `https://www.altinn.no/api/metadata/codelists/` api when testing (it should not be down often?), or does it make sense to add more logic in order to be able to mock the requests. I feel like it should be safe to assume Norway will never be removed from `ASF_land` regardless of the situation in the world currently.

**Comment by RonnyB71** [comment]
> I'm not very experienced writing tests. What do you think I should focus on here?
> 
> Possible focus areas:
> 
> * Service registration works, and correctly stores and provides the `filter` and `map` function.
> * `metadata/codelists` endpoint still works and returns data that matches the definitions.
> * Memory cache works correctly
> * filter and map is correctly applied.
> * Any thing I missed?
> 
> Do you think it is OK to actually call the `https://www.altinn.no/api/metadata/codelists/` api when testing (it should not be down often?), or does it make sense to add more logic in order to be able to mock the requests. I feel like it should be safe to assume Norway will never be removed from `ASF_land` regardless of the situation in the world currently.

As for your last question first, I'm neither familiar with the Altinn 2 side of things or if we have done integration tests like that previously. @SandGrainOne do you have any thoughts on this? Do we have tests calling external api's? Should we have it? The reason why I'm hesitating a bit is that for tests like this we currently don't have any (I think) that require an environment to be up and running - all tests run on the agent and mock external dependencies. We do have end-2-end tests driving different critical scenarios and regression tests, but that is a different story.

I think a small test to verify that the service is registered is good to have since we will include this in all apps. As for the other points I think you are touching upon good areas for tests. I normally start with one or two tests along the critical path of what I'm trying to achieve, run the tests and let the test coverage report guide me from there to make sure I have enough coverage. Then I take another look and see if I missed some negative and/or edge cases. In your case, how should the provider react if the Altinn 2 side is down - throw exception, return null or return empty list. I just changed the options controller to return 404 in cases where the specified option id doesn't exists, but return an empty list if the id is found but there are no valid values.

I you take a look in the Altinn.App.PlatformServices.Test project under Options and in the App.IntegrationTestsRef proejct under ApiTests/OptionsApiTests you'll find the ones I've written to cover the basics regarding options.

**Review by altinnadmin — APPROVED** [review]
LGTM

**Pull request merged**
