### PR TITLE
Revert "Remove link to altinn-din from app-template"

### PR DESCRIPTION
**Pull request by tjololo**
Change of font caused breaking changes. Reverting removal of altinn-din

### CODE REVIEW

**Comment by ivarne** [comment]
5 months? Should this be done in all apps created in that timeframe too?

**Comment by tjololo** [comment]
> 5 months? Should this be done in all apps created in that timeframe too?

There has not been any releases of the template so no apps are affected by the removal

**Comment by olemartinorg** [comment]
@bjosttveit Do we need this, or can we load the font CSS via app-frontend?

**Comment by bjosttveit** [comment]
> @bjosttveit Do we need this, or can we load the font CSS via app-frontend?

I would much rather have app-frontend be in control of the font, and we simply need to switch the css import from inter to altinn-din (it has its own css file with font-face definitions) and then switch the `font-family`. That way we wont have apps loading unecessary assets when we eventually switch to something else.

image

**Comment by tjololo** [comment]
Removing it is fine by me, does version 3 of app-frontend load the font?
We can remove it again when we upgrade the tempate to version 4 if version 3 doesn't manage it by it self

**Comment by bjosttveit** [comment]
Right, v3 does not currently load the font itself, and still relies on this being set in the template

**Review by olemartinorg — APPROVED** [review]

**Comment by bjosttveit** [comment]
I created a branch for changes related to frontend v4 [here](https://github.com/Altinn/app-template-dotnet/compare/main...fe-v4)

**Pull request merged**
